### ISSUE TITLE
Script does not create scheduled tasks, and does not work if directories scripts and tasks are not in its directory

### ISSUE THREAD

**Issue by selivan** [jgregmac/hyperv-fix-for-devs#2] opened 2021-07-10 20:41 UTC
```
PS C:\Users\selivan\work> .\Install-DeveloperFix.ps1
Copy-Item : Cannot find path 'C:\Users\selivan\work\scripts' because it does not exist.
At C:\Users\selivan\work\Install-DeveloperFix.ps1:76 char:5
+     Copy-Item -Path (Join-Path -Path $ScriptSource -ChildPath "*.ps1" ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\selivan\work\scripts:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
```

After I create directories `scripts` and `tasks` (it also asked for the second one):

```
PS C:\Users\selivan\work> .\Install-DeveloperFix.ps1
Join-Path : Cannot find path 'C:\Users\selivan\AppData\Local\Temp\tasks\login-task.xml' because it does not exist.
At C:\Users\selivan\work\Install-DeveloperFix.ps1:101 char:19
+ ... ourceFile = Join-Path -Path $TaskStage -ChildPath login-task.xml -Res ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\seliva...\login-task.xml:String) [Join-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.JoinPathCommand

Get-Content : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\selivan\work\Install-DeveloperFix.ps1:102 char:46
+     Register-ScheduledTask -Xml (Get-Content $SourceFile | Out-String ...
+                                              ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Content], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.GetContentCommand

Join-Path : Cannot find path 'C:\Users\selivan\AppData\Local\Temp\tasks\shutdown-task.xml' because it does not exist.
At C:\Users\selivan\work\Install-DeveloperFix.ps1:105 char:19
+ ... ourceFile = Join-Path -Path $TaskStage -ChildPath shutdown-task.xml - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\seliva...utdown-task.xml:String) [Join-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.JoinPathCommand

Get-Content : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\selivan\work\Install-DeveloperFix.ps1:106 char:46
+     Register-ScheduledTask -Xml (Get-Content $SourceFile | Out-String ...
+                                              ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Content], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.GetContentCommand

```

Disabled network adapter "Hyper-V Fix" was created, but it failed to create scheduled tasks.

P.S. I am migrating to Windows after being on Linux for a long time, so I can't say I well understand what is happening here...

**Comment by jgregmac** [comment] 2021-07-12 15:24
I have added a logging module and more verbose output to the install script.  If you want to try the new version, please post and new script output here, and I will see what I can do to troubleshoot.

Please note that your errors could be caused by permissions problems.  There are two different "New-Item" commands in the script that create the directories needed for staging the scheduled tasks, and to host the startup/shutdown scripts.  If these commands fail, the rest of the script cannot proceed.  However, in the current code, the script should just halt after any errors.  This should give you a better idea what the root issue might be.

Welcome to Windows... it's a strange place for Linux users, but not really as bad as everyone likes to say. (But also not as good a MS likes to claim, either...)

**Comment by selivan** [comment] 2021-07-12 22:07
Well, I kinda already made this: https://selivan.github.io/2021/07/12/wsl-set-static-subnet-hack.html You are mentioned, of course.

Experimenting with your script and dummy network interfaces led me to not working system, that I fixed from Safe Mode by removing broken adapter in device manager. So I am not eager to experiment more, I need this machine for work.

> it's a strange place for Linux users

It sure is :)

**Comment by jgregmac** [comment] 2021-07-21 13:51
Closing as the issue is based off an older version of the solution, and is not reproducible.

**Closed as completed by jgregmac** 2021-07-21 13:51 UTC
